---
########
########
## CI ##
########
########
name: Continuous Integration

#
# Documentation:
# https://help.github.com/en/articles/workflow-syntax-for-github-actions
#

#############################
# Start the job on all push #
#############################
# Don't need to run on push to master/main
on:
  push:
    branches-ignore:
      - 'master'
      - 'main'

###############
# Set the Job #
###############
jobs:
  build:
    # Name the Job
    name: CI
    # Set the agent to run on
    runs-on: ubuntu-latest
    ##################
    # Load all steps #
    ##################
    steps:
      ##########################
      # Checkout the code base #
      ##########################
      - name: Checkout Code
        uses: actions/checkout@v2

      ########################
      # Setup Docker build X #
      ########################
      - name: Setup BuildX
        uses: docker/setup-buildx-action@v1

      ##############################
      # Build the docker container #
      ##############################
      - name: Build Docker container
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          build-args: |
            BUILD_DATE=${{ env.BUILD_DATE }}
            BUILD_REVISION=${{ github.sha }}
            BUILD_VERSION=${{ github.sha }}
          push: false
          
     # Upload an artifact to GitHub
      - name: Upload Artifact to Github Build Job
        uses: actions/upload-artifact@v2
        if: success()
        with:
           name: test-build-artifact
           path: test.txt
           
  deploy:
    name: Deploy Job
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download Artifact from Github Build Job
        uses: actions/download-artifact@v2
        with:
          name: test-build-artifact
      - name: Deploy Artifact      
        run: cat test.txt

